LR12/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users
  get 'users/show' => 'users#show'
  root 'seq#input'
  get '/input' => 'seq#input'
  post '/show' => 'seq#show'
end

LR12/app/models/seq_show.rb
# frozen_string_literal: true

class SeqShow
  include ActiveModel::Model # примешиваем методы для модели из ActiveModel
  include ActiveModel::Validations # примешиваем методы для валидаций из ActiveModel
  attr_accessor :num, :str

  validates :num, :str, presence: { message: 'не может быть пустым' }
  validates :num, format: { with: /\A\d+\z/, message: 'должен быть натуральным числом' }
  validates :str,
            format: { with: /\A-?\d+(\d+)?(\s-?\d+(\d+)?)*\s*\z/,
                      message: 'должна быть последовательностью чисел' }

  def length_valid?
    errors.add(:str, ":длина не равна #{num}") if str.split(' ').length != num.to_i
  end

  validate :length_valid?
end

LR12/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include ActiveModel::Serializers::Xml

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

LR12/app/controllers/application_controller.rb
# frozen_string_literal: true

# application
class ApplicationController < ActionController::Base
  helper_method :current_user, :signed_in?

  private

  def current_user
    @current_user ||= session[:user_id] &&
                      User.find_by_id(session[:user_id])
  end

  def signed_in?
    current_user.present?
  end

  def no_authorize
    return unless signed_in?

    flash[:warning] = 'Вы уже авторизованы'
    redirect_to root_path
  end

  def authorize
    return if signed_in?

    flash[:warning] = 'Вы не авторизованы'
    redirect_to new_session_path
  end
end

LR12/app/controllers/seq_controller.rb
# frozen_string_literal: true

# operates with a sequence
class SeqController < ApplicationController
  include SeqHelper

  before_action :authorize

  def input; end

  def show
    @seq = SeqShow.new(seq_params)
    m = perfect(seq)
    @all_seqs = m[0]
    @count = m[1]
    @longest = @all_seqs.max { |s1, s2| s1.split(' ').length <=> s2.split(' ').length }
  end

  private

  def seq_params
    params.permit(:num, :str)
  end
end

LR12/app/controllers/sessions_controller.rb
# frozen_string_literal: true

# sessions
class SessionsController < ApplicationController
  before_action :no_authorize, only: %i[new create]
  before_action :authorize, only: :destroy

  def new; end

  # rubocop:disable Metrics/AbcSize
  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Добро пожаловать, #{user.name}!"
      redirect_to root_url
    else
      flash[:error] = 'Неверный логин и/или пароль'
      redirect_to new_session_path
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    @_current_user = session[:user_id] = nil
    redirect_to new_session_path
  end
end

LR12/app/controllers/users_controller.rb
# frozen_string_literal: true

# users
class UsersController < ApplicationController
  before_action :authorize, except: %i[new create]
  before_action :no_authorize, only: %i[new create]

  # GET /users/new
  def new; end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Добро пожаловать, #{@user.name}!"
      redirect_to root_path
    else
      redirect_to new_user_path, notice: 'Ошибка во вводе данных или вы уже зарегистрированы'
    end
  end

  def show
    @users = User.select(:id, :name, :email, :created_at, :updated_at)
    render xml: @users
  end

  private

  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
end

LR12/app/helpers/seq_helper.rb
# frozen_string_literal: true

# operates with a sequence
module SeqHelper
  def seq = params[:str]
  def len = params[:num]

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def perfect(seq_str)
    seq = seq_str.chomp.split(' ').map(&:to_i)
    count = 0
    all_seqs = []
    curr_seq = []
    match = false
    seq.each_index do |ind|
      num = seq[ind]
      sum = 0
      1.upto(num / 2) do |del| # проверяем, является ли num совершенным числом
        sum += del if (num % del).zero?
      end
      if (num == sum) & (num != 0) # если совершенное
        curr_seq.push(num.clone)
        match = true
      elsif match
        all_seqs.push(curr_seq.clone.join(' '))
        curr_seq.clear
        match = false
        count += 1
      end
    end

    if match
      all_seqs.push(curr_seq.clone.join(' '))
      curr_seq.clear
      match = false
      count += 1
    end
    [all_seqs, count] # массив строк и число
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength
end

LR12/app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

LR12/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

LR12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
  <nav class="navbar navbar-light bg-light">
    <ul class = "nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if signed_in? %>        
            <li><%= link_to 'Последовательность', input_path, class: 'nav-link px-2' %></li>
            <li><%= link_to 'Все пользователи', users_show_path, class: 'nav-link px-2' %></li>
          <% end %>
    </ul>

    <ul class = "nav col-12 col-lg-auto mb-2 mb-md-0">
      <% if signed_in? %>
          <span class="navbar-brand mb-0 h1"><%= current_user.name %></span>          
          <li><%= link_to 'Выйти', session_path, data: {turbo_method: :delete}, class: 'nav-link px-2', id: 'quit_button' %></li>
      <% else %>
          <li><%= link_to 'Регистрация', new_user_path, class: 'nav-link px-2' %></li>
          <li><%= link_to 'Вход', new_session_path, class: 'nav-link px-2' %></li>
      <% end %>
    </ul>
  </nav>
  </header>
  
  <body>
    <div class = "container">
    <% flash.each do |type, msg| %>
      <div class='alert alert-info'>
        <strong id='msg'><%= msg %></strong>
      </div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

LR12/app/views/seq/_show_message.erb
<% if @seq.valid? %>  
    <% if @count>0 %>
        <p>Все отрезки:</p>
        <table border=1>
            <tr>            
                <td>
                    №
                </td> 
                <td>
                    отрезок 
                </td>                   
            </tr>
            <% adder=0%>   
            <% @all_seqs.each do |stroka| %>    
                <tr>            
                    <td>
                        <%= adder+=1%>
                    </td> 
                    <td>
                    <center> <%= stroka %>  </center> 
                    </td>                   
                </tr>
            <% end %>
        </table>

        <p> Самый длинный отрезок:</p>
        <div id='longest'>
            <%= @longest %> 
        </div>

        <p> Количество отрезков:</p>
        <div id='count'> <%= @count %> </div>
        <br><br>

    <% else %>
    В последовательности нет совершенных чисел
    <% end %>

<% else %>
 <h2>Ошибки ввода:</h2>
  <ul>
    <% @seq.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

LR12/app/views/seq/input.html.erb
<%= form_with url: show_path do |form| %>
    <table>
        <tr>
            <td>
                <%= form.label("Введите количество чисел: ") %>
            </td>
            <td>
                <%= form.text_field :num, :value => 10 %> <br>
            </td>
        </tr>
        <tr>
            <td>
                <%= form.label("Введите последовательность: ") %>
            </td>
            <td>
                <%= form.text_field :str, :value => "6 28 3 4 5 6 6 496 3 6" %> <br>
            </td>
        </tr>
        <tr>
            <td>
                <%= form.submit("Вывести", id: 'submit') %>
            </td>
        </tr>
    </table>  
<% end %>
<div id='show-container'></div>

LR12/app/views/seq/show.turbo_stream.erb
<%= turbo_stream.update 'show-container', partial: 'show_message' %>

LR12/app/views/users/new.html.erb
<h1 class="mb-4">Регистрация</h1>

<%= form_with url: users_path do |form| %>
  <div class = "mb-3 row">
    <div class = "col-sm-2 col-form-label">
      <%= form.label :name %>
    </div>
    
    <div class = "col-sm-10">
      <%= form.text_field :name, class: 'form-control form-control-lg', id:'name_field' %>
    </div>
  </div>

  <div class = "mb-3 row">
    <div class = "col-sm-2 col-form-label">
      <%= form.label :email %>
    </div>

    <div class = "col-sm-10">
      <%= form.email_field :email, class: 'form-control form-control-lg', id: 'email_field' %>
    </div>
  </div>

  <div class = "mb-3 row">
    <div class = "col-sm-2 col-form-label">
      <%= form.label :password %>
    </div>

    <div class = "col-sm-10">
      <%= form.password_field :password, class: 'form-control form-control-lg', id:'password_field' %>
    </div>
  </div>

  <div class = "mb-3 row">
    <div class = "col-sm-2 col-form-label">
      <%= form.label :password_confirmation%>
    </div>

    <div class = "col-sm-10">
      <%= form.password_field :password_confirmation, class: 'form-control form-control-lg', id: 'password_confirmation_field' %>
    </div>
  </div>

  <p><%= form.submit("Зарегистрироваться", id: 'btn_submit', class: 'btn btn-primary') %></p>
<% end %>